language: cpp
cache: ccache

notifications:
  email:
    - amarburg@apl.washington.edu

# Per-OS configuration
matrix:
  env:
    - BUILD_TYPE=release
#    - BUILD_TYPE=Debug
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install rake ; fi
  - rake dependencies:travis:$TRAVIS_OS_NAME

script: rake debug:test release:test


## Try caching these ExternalProjects.   I believe the CMake dependency
## process will correctly rebuild these if upstream changes.
cache:
  directories:
  - build_ci/g2o
  - build_ci/g3log
  - build_ci/google-snappy
  - build_ci/Pangolin
