language: cpp

# Per-OS configuration
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3


## Install OSX deps using a script
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then .travis/before_install_osx.sh        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travis/before_install_trusty.sh     ; fi

script: .travis/build.sh
